[student]
name = 'Nenashev Sergey'
group = '4842'
number = '19'

[server]
host = '0.0.0.0'
port = 8080

[aws]
region = 'eu-central-1'

[s3]
bucket = 'nenashev'

[database]
host = 'database-1.clhbct1n77at.eu-central-1.rds.amazonaws.com'
port = 3306
user = 'admin'
password = '11111111'
dbname = 'suai'
